- name: Download Brew install script
  become_user: "{{ ansible_env.SUDO_USER }}"
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install_brew.sh
    mode: 0755
  when: state_brew == "present"

- name: Install Brew
  become_user: "{{ ansible_env.SUDO_USER }}"
  shell: ./install_brew.sh
  args:
    executable: /bin/bash
    chdir: /tmp/
  when: state_brew == "present"

- name: Setup user profile
  shell: |
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/{{ ansible_env.SUDO_USER }}/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  args:
    executable: /bin/bash
