- name: Install KVM
  apt:
    name:
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils
    - virt-manager
    - virtinst

- name: Register KVM (libvirtd) Daemon
  systemd:
    enabled: yes
    name: libvirtd

- name: Add current user to kvm group
  user:
    name: {{ ansible_user_id }}
    uid: {{ ansible_user_gid }}
    group: kvm

- name: Add current user to libvirt group
  user:
    name: {{ ansible_user_id }}
    uid: {{ ansible_user_gid }}
    group: libvirt

- name: Create network bridge config
  copy:
    dest: /etc/netplan/01-netcfg.yaml
    content: |
    network:
      ethernets:
        enp39s0:
          dhcp4: false
          dhcp6: false
      bridges:
        br0:
          interfaces: [enp39s0]
          dhcp4: false
          addresses: [192.168.1.162/24]
          macaddress: 08:00:27:4b:1d:45
          routes:
            - to: default
              via: 192.168.1.1
              metric: 100
          nameservers:
            addresses: [8.8.8.8]
          parameters:
            stp: false
          dhcp6: false
      version: 2