# https://trendoceans.com/install-pipewire-on-debian-11/

- name: Install PipeWire
  apt:
    name:
      - pipewire 
      - pipewire-audio-client-libraries

- name: Create Pipewire session file
  file:
    path: /etc/pipewire/media-session.d/with-pulseaudio
    owner: 1000
    group: 1000
    mode: '0644'

- name: Copy Pipewire Pulse Service Files
  copy:
    src: /usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.*
    dest: /etc/systemd/user/

- name: Stop and Deregister PulseAudio Service
  systemd:
    enabled: no
    scope: user
    state: stopped
    masked: yes
    name: pulseaudio.service

- name: Stop and Deregister PulseAudio Socket
  systemd:
    enabled: no
    scope: user
    state: stopped
    name: pulseaudio.socket

- name: Start and Register Pipewire Service
  systemd:
    daemon_reload: yes
    enabled: yes
    scope: user
    state: started
    name: pipewire

- name: Start and Register Pipewire-Pulse Service
  systemd:
    daemon_reload: yes
    enabled: yes
    scope: user
    state: started
    name: pipewire-pulse

  - name: Check if PipeWire is now properly active
    command: pactl info | grep PipeWire
