# Ansible facts available: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:
  - name: Clean unwanted pre-installed packages
    apt:
      name:
        - firefox-esr
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: Install basic utilities
    apt:
      name:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - lsb-release
        - gnupg2
        - wget
        - curl
        - snapd

  - name: Install basic dev utilities
    apt:
      name:
        - git
        - vim
        - tree
        - htop
        - vim
  
  - name: Install PipeWire (System Sound)
    include: tasks/pipewire.yml
  
  - name: Install VSCode
    include: tasks/vscode.yml

  - name: Install Docker
    include: tasks/docker.yml

  - name: Install Apt Packages
    apt:
      name:
        - net-tools
        - rdesktop
        - telegram-desktop

  - name: Install firefox
    snap:
      name:
        - firefox

  - name: Install Wine
    include: tasks/wine.yml

  - name: Install Signal
    include: tasks/signal.yml

  - name: Install Snap Packages
    snap:
      name:
        - cura-slicer
        - discord
        - moonlight
        - slack
        - bpytop
        - chromium
        - discord

  - name: Apt cleanup
    apt:
      autoremove: yes
      clean: yes

  # - name: Install Tools and Utilities
  #   apt:
  #     name:
  #       - vlc
  #       - winetricks
